drivers: misc: pn5xx: fix compilation error/warning for linux 6.12
'no_llseek' is deprecated in linux 6.12
According with below commit:
  cb787f4ac0c2 [tree-wide] finally take no_llseek out

Build error/warning log:
  error: ‘no_llseek’ undeclared here
  warning: no previous prototype for ‘pn54x_remove’ [-Wmissing-prototypes]