ARM64: configs: tn_imx8_defconfig: enable configs to ubuntu SNAP support
- Enable CONFIG_SQUASHFS_XZ to support snapd:
[   73.993805] Filesystem uses "xz" compression. This is not supported
error: system does not fully support snapd: cannot mount squashfs image
using "squashfs": mount: /tmp/sanity-mountpoint-066601217: wrong fs type
, bad option, bad superblock on /dev/loop0, missing codepage or helper
program, or other error.

- Enable CONFIG_SQUASHFS_LZO to support ubuntu-frame
Mount snap "ubuntu-frame" (446)
|[  128.282476] Filesystem uses "lzo" compression. This is not supported

- Enable CONFIG_CGROUP_FREEZER to support ubuntu-frame
snap "ubuntu-frame" (run hook "prepare-plug-graphics-core20":
cannot open cgroup hierarchy /sys/fs/cgroup/freezer:
No such file or directory)